sudo: false
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn run build
  - yarn run build:docs

branches:
  only:
    - master
    - dev
